### ISSUE TITLE
ceas: missing python module six when running data_manager_ceas_fetch_annotations.py

### ISSUE THREAD

**Issue by loraine-gueguen** [fls-bioinformatics-core/galaxy-tools#16] opened 2016-07-25 10:04 UTC
Hi,

I have the following error message when running the data manager "Fetch ceas annotations" (installed from https://toolshed.g2.bx.psu.edu/view/pjbriggs/ceas/f411ce97a351):

`Traceback (most recent call last):
  File "/w/galaxy/galaxydev/shed_tools/toolshed.g2.bx.psu.edu/repos/pjbriggs/ceas/f411ce97a351/ceas/data_manager/data_manager_ceas_fetch_annotations.py", line 13, in <module>
    from galaxy.util.json import from_json_string, to_json_string
  File "/w/galaxy/galaxydev/galaxy/lib/galaxy/util/__init__.py", line 30, in <module>
    from six import binary_type, iteritems, PY3, string_types, text_type
ImportError: No module named six`

If I set the environment properly with the dependencies, run python and try to load the six module, I have the same error:

[lgueguen@galaxy2 694]$ PACKAGE_BASE=/w/galaxy/galaxydev/shed_tools_tool_dependency_dir/python_mysqldb/1.2.5/pjbriggs/ceas/f411ce97a351; export PACKAGE_BASE; . /w/galaxy/galaxydev/shed_tools_tool_dependency_dir/python_mysqldb/1.2.5/pjbriggs/ceas/f411ce97a351/env.sh; PACKAGE_BASE=/w/galaxy/galaxydev/shed_tools_tool_dependency_dir/bx_python/0.7.1/pjbriggs/ceas/f411ce97a351; export PACKAGE_BASE; . /w/galaxy/galaxydev/shed_tools_tool_dependency_dir/bx_python/0.7.1/pjbriggs/ceas/f411ce97a351/env.sh; PACKAGE_BASE=/w/galaxy/galaxydev/shed_tools_tool_dependency_dir/cistrome_ceas/1.0.2.d8c0751/pjbriggs/ceas/f411ce97a351; export PACKAGE_BASE; . /w/galaxy/galaxydev/shed_tools_tool_dependency_dir/cistrome_ceas/1.0.2.d8c0751/pjbriggs/ceas/f411ce97a351/env.sh
[lgueguen@galaxy2 694]$ which python
/w/galaxy/galaxydev/shed_tools_tool_dependency_dir/bx_python/0.7.1/pjbriggs/ceas/f411ce97a351/venv/bin/python
[lgueguen@galaxy2 694]$ python
Python 2.7.2 (default, Oct 25 2013, 17:46:02) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more  #information.
>>> import six
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named six

A new addition in tool_dependencies.xml (in tag <action type="setup_virtualenv"> for <package name="bx_python" version="0.7.1">) could perhaps solve this issue:

`six==1.10.0`

or add a dependency to package https://toolshed.g2.bx.psu.edu/view/iuc/package_python_2_7_six_1_10_0/6944ba405057

Regards,

Loraine Guéguen

**Comment by pjbriggs** [comment] 2016-07-26 10:15
Hello @loraine-gueguen 

Thanks for the bug report, sorry you've encountered problems.

Looking at this briefly, I wonder if it's due to changes in the Galaxy source code from which the data manager imports the JSON encoder/decoder functions from, specifically this line in the data manager Python code appears to be the source of the problem:

    from galaxy.util.json import from_json_string, to_json_string

In Galaxy version 15.10 (which we're using here) and earlier `galaxy.util` doesn't appear to have the dependency on the `six` package.

However I will investigate some more - if this is the issue then I'll probably look at dropping the dependency on `galaxy.util`. I'll be in touch when I get a chance to look into this properly.

Thanks for your interest in our Galaxy tools!

Peter

**Comment by loraine-gueguen** [comment] 2016-07-27 14:39
We use Galaxy release_16.04
Thanks for you answer.

**Comment by pjbriggs** [comment] 2016-08-11 14:16
Hello @loraine-gueguen 

Thanks for confirming the version of your Galaxy installation, I was finally able to test on v16.04 and reproduce the error that you reported.

I've now fixed the problem so that I should work on your installation - there is an updated version available on the main toolshed, so if you'd like to try that then please let me know what happens.

Thanks again for using our Galaxy tools, best wishes

Peter

**Comment by loraine-gueguen** [comment] 2016-08-16 15:40
Thanks @pjbriggs 
I have tested and it works now!

**Comment by pjbriggs** [comment] 2016-08-17 08:08
@loraine-gueguen great, thanks for letting me know.

**Closed by pjbriggs** 2016-08-17 08:08 UTC
